# Logging
logging.config: classpath:log4j2.xml

# Tomcat
server:
    address: 127.0.0.1
    port: 8147
    compression:
        enabled: true
        mime-types: application/javascript, text/css
        min-response-size: 1024

# wechat-login-demo
wechat_jump_login:
    app_id: wx1234567890abcdef
    app_secret: 1234567890abcdef1234567890abcdef
    redirect_url: https://www.incarcloud.com/oauth2/wechat
    jump_ticket: xxxxxxxx